services:
  app:
    build: .
    container_name: nest-app
    ports:
      - "3100:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://mephiscus:devilMayCry5@db:5432/bh
    depends_on:
      - db
    command: ["sh", "-c", "./docker-start.sh"]
    volumes:
      - ./media:/app/media
    dns:
      - 8.8.8.8
      - 1.1.1.1

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: mephiscus
      POSTGRES_PASSWORD: devilMayCry5
      POSTGRES_DB: bh
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "3101:5432"

  app-shell:
    build: .
    container_name: nest-shell
    command: sh
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://mephiscus:devilMayCry5@db:5432/bh
    depends_on:
      - db

volumes:
  pgdata:
